name: Congratulations


on:
  push:
    branches:
      - main
  schedule:
  - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  congratulate:
    runs-on: ubuntu-24.04
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Groovy
      uses: wtfjoke/setup-groovy@v2
      with:
        groovy-version: '4.x'
    - run: groovy congratulations.groovy
      env: 
        PERSONAL_DATA: ${{ vars.PERSONAL_DATA }}
        BOT_BEARER_TOKEN: ${{ secrets.BOT_BEARER_TOKEN }}
