name: Continuous Delivery

on:
  schedule:
  - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  congratulate:
    runs-on: ubuntu-24.04
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Groovy
      uses: wtfjoke/setup-groovy@v2
      with:
        groovy-version: '2.9'
    - run: groovy congratulations.groovy
      env: 
        PERSONAL_DATA: ${{ secrets.PERSONAL_DATA }}
        BOT_BEARER_TOKEN: ${{ secrets.BOT_BEARER_TOKEN }}